version: '3.3'
services:
  nginxpm:
    image: jc21/nginx-proxy-manager:latest
    environment:
      DISABLE_IPV6: 'true'
    ports:
     - 80:80
     - 81:81
     - 443:443
    volumes:
     - /mnt/nginxpm/config.json:/app/config/production.json
     - /mnt/nginxpm/data:/data
     - /mnt/letsencrypt:/etc/letsencrypt
    networks:
     - odoo 
    logging:
      driver: none
    deploy:
      restart_policy:
        condition: on-failure
        
  
  smtp:
    image: ghcr.io/viraweb123/postfixadmin-postfix:0.1.0
    environment:
      ALLOW_EMPTY_SENDER_DOMAINS: 'true'
      FORCE_COLOR: '1'
      INBOUND_DEBUGGING: '0'
      POSTFIX_DB_HOST: postgres13
      POSTFIX_DB_NAME: postfixadmin
      POSTFIX_DB_PASSWORD: odoo
      POSTFIX_DB_TYPE: pgsql
      POSTFIX_DB_USER: odoo
      POSTFIX_mynetworks: 11.0.0.0/16
      POSTFIX_mynetworks_style: subnet
      TZ: Europe/Amsterdam
    networks:
     - odoo
    logging:
      driver: none
    deploy:
      restart_policy:
        condition: on-failure
  
  
  postgres13:
    image: postgres:13
    labels:
      com.dgyar.department: IT
      com.dgyar.description: Data node
    environment:
      PGDATA: /var/lib/postgresql/data/pgdata
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: odoo
      POSTGRES_USER: odoo
    volumes:
     - /mnt/postgresql:/var/lib/postgresql/data/pgdata
    networks:
     - odoo
    logging:
      driver: none
    deploy:
      restart_policy:
        condition: on-failure
  odoo14:
    image: odoo:14.0
    environment:
      test: test
    volumes:
     - /mnt/odoo/data:/var/lib/odoo
     - /mnt/odoo/addons-14:/mnt/extra-addons
     - /mnt/odoo/odoo-14.conf:/etc/odoo/odoo.conf
    networks:
     - odoo
    logging:
      driver: none
    deploy:
      restart_policy:
        condition: on-failure		
      
    
networks:
  
  odoo:
  
